<?php

namespace DocsifyDocs;

if ( ! defined( 'WPINC' ) ) {
    die;
}

/**
 * Blocks direct web access to the documentation directory.
 *
 * Serving the files through WordPress is only worth something while the same
 * files cannot be fetched straight off disk, which on Apache means a deny rule
 * next to them. Servers without .htaccess support need the equivalent rule in
 * their own configuration.
 */
class Hardening {

    private const FILE   = '.htaccess';
    private const MARKER = '# BEGIN Docsify Docs';

    /**
     * Keeps the deny rule in step with the protection setting.
     */
    public function sync(): void {
        if ( Docs::isProtected() ) {
            $this->write();
            return;
        }

        $this->remove();
    }

    private function write(): void {
        $filesystem = $this->filesystem();

        if ( ! $filesystem ) {
            return;
        }

        $path = $this->path();

        if ( $filesystem->exists( $path ) && ! $this->isOurs( $filesystem->get_contents( $path ) ) ) {
            return;
        }

        $filesystem->put_contents( $path, $this->rules(), FS_CHMOD_FILE );
    }

    private function remove(): void {
        $filesystem = $this->filesystem();

        if ( ! $filesystem ) {
            return;
        }

        $path = $this->path();

        if ( ! $filesystem->exists( $path ) || ! $this->isOurs( $filesystem->get_contents( $path ) ) ) {
            return;
        }

        $filesystem->delete( $path );
    }

    /**
     * @param string|false $contents
     */
    private function isOurs( $contents ): bool {
        return is_string( $contents ) && strpos( $contents, self::MARKER ) === 0;
    }

    private function path(): string {
        return trailingslashit( Docs::dir() ) . self::FILE;
    }

    private function rules(): string {
        return self::MARKER . "\n"
            . "# Generated by the Docsify Docs plugin. Documentation files are served\n"
            . "# by WordPress so the access rule applies to them as well.\n"
            . "<IfModule mod_authz_core.c>\n"
            . "    Require all denied\n"
            . "</IfModule>\n"
            . "<IfModule !mod_authz_core.c>\n"
            . "    Order allow,deny\n"
            . "    Deny from all\n"
            . "</IfModule>\n"
            . "# END Docsify Docs\n";
    }

    private function filesystem(): ?\WP_Filesystem_Base {
        if ( ! function_exists( 'WP_Filesystem' ) ) {
            require_once ABSPATH . 'wp-admin/includes/file.php';
        }

        global $wp_filesystem;

        if ( ! WP_Filesystem() || ! $wp_filesystem->is_dir( Docs::dir() ) ) {
            return null;
        }

        return $wp_filesystem;
    }
}
